language: ruby
rvm:
  - 2.2
before_install:
  - gem update --system
  - gem --version
script:
  - bundle install
  - jekyll build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
